import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/app/components/header";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}>
          <Header />
          {children}
          <footer className="py-4 row-start-3 flex gap-6 flex-wrap items-center justify-center">
            <p>
              Made with 💖 by{" "}
              <Link target="_blank" className="text-blue-600" href={`https://chocos.vercel.app`}>
                chocoscoding
              </Link>
            </p>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
